# Generated by Django 5.2.5 on 2025-08-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('spotify_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('ranked_show_ids', models.JSONField(default=list)),
                ('disliked_ids', models.JSONField(default=list)),
            ],
        ),
    ]
